# Generated by Django 6.1 on 2026-08-26 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_employee_age_employee_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='attendance_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employee',
            name='last_login_attendance',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
